/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.usta.test1.gui;
import co.edu.usta.test1.controller.StudentController;
import co.edu.usta.test1.logic.Faculty;
import co.edu.usta.test1.logic.Student;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author suare
 */
public class mainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindow
     */
    private StudentController studentController;
    private boolean oned;
    private boolean onem;
    private boolean oney;
    public mainWindow() {
        studentController = new StudentController();        
        oned = false;
        onem = false;
        oney = false;
        initComponents();
        txtEspacioVacio.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStudentBornDate2 = new javax.swing.JTextField();
        lblStudentID = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        lblStudentWeight = new javax.swing.JLabel();
        lblStudentHeight = new javax.swing.JLabel();
        lblStudentBornDate = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        lblStudentGender = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        lblSchoolID = new javax.swing.JLabel();
        lblSchoolName = new javax.swing.JLabel();
        lblSchool = new javax.swing.JLabel();
        txtStudentBornDateDay = new javax.swing.JTextField();
        txtStudentName = new javax.swing.JTextField();
        txtStudentGender = new javax.swing.JTextField();
        txtStudentHeight = new javax.swing.JTextField();
        txtStudentWeight = new javax.swing.JTextField();
        txtSchoolID = new javax.swing.JTextField();
        txtSchoolName = new javax.swing.JTextField();
        btnDone = new javax.swing.JButton();
        lblStudentCode = new javax.swing.JLabel();
        txtStudentCode = new javax.swing.JTextField();
        txtEspacioVacio = new javax.swing.JLabel();
        txtStudentBornDateMonth = new javax.swing.JTextField();
        txtStudentBornDateYear = new javax.swing.JTextField();
        txtStudentLastName = new javax.swing.JTextField();
        lblStudentLastName = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        txtStudentBornDate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentBornDate2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        lblStudentID.setText("ID");

        lblStudentName.setText("Name");

        lblStudentWeight.setText("Weight");

        lblStudentHeight.setText("Height");

        lblStudentBornDate.setText("Born Date");

        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });

        lblStudentGender.setText("Gender");

        lblStudent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblStudent.setText("Student");

        lblSchoolID.setText("ID");

        lblSchoolName.setText("Name");

        lblSchool.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSchool.setText("School");

        txtStudentBornDateDay.setForeground(new java.awt.Color(204, 204, 204));
        txtStudentBornDateDay.setText("dd");
        txtStudentBornDateDay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStudentBornDateDayMouseClicked(evt);
            }
        });
        txtStudentBornDateDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentBornDateDayActionPerformed(evt);
            }
        });

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        txtStudentGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentGenderActionPerformed(evt);
            }
        });

        txtStudentHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentHeightActionPerformed(evt);
            }
        });

        txtStudentWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentWeightActionPerformed(evt);
            }
        });

        txtSchoolID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolIDActionPerformed(evt);
            }
        });

        txtSchoolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSchoolNameActionPerformed(evt);
            }
        });

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        lblStudentCode.setText("Code");

        txtStudentCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentCodeActionPerformed(evt);
            }
        });

        txtEspacioVacio.setForeground(new java.awt.Color(255, 0, 0));
        txtEspacioVacio.setText("Tiene que llenar todos los espacios");

        txtStudentBornDateMonth.setForeground(new java.awt.Color(204, 204, 204));
        txtStudentBornDateMonth.setText("mm");
        txtStudentBornDateMonth.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStudentBornDateMonthMouseClicked(evt);
            }
        });
        txtStudentBornDateMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentBornDateMonthActionPerformed(evt);
            }
        });

        txtStudentBornDateYear.setForeground(new java.awt.Color(204, 204, 204));
        txtStudentBornDateYear.setText("yyyy");
        txtStudentBornDateYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStudentBornDateYearMouseClicked(evt);
            }
        });
        txtStudentBornDateYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentBornDateYearActionPerformed(evt);
            }
        });

        txtStudentLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentLastNameActionPerformed(evt);
            }
        });

        lblStudentLastName.setText("Last Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSchool)
                        .addGap(362, 362, 362))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSchoolID)
                                    .addComponent(lblSchoolName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSchoolID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStudentID)
                                    .addComponent(lblStudentName)
                                    .addComponent(lblStudentLastName)
                                    .addComponent(lblStudentWeight)
                                    .addComponent(lblStudentHeight)
                                    .addComponent(lblStudentBornDate)
                                    .addComponent(lblStudentGender)
                                    .addComponent(lblStudentCode))
                                .addGap(143, 143, 143)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtStudentBornDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentBornDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStudentBornDateYear))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStudent)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEspacioVacio)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnDone)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStudentID)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentHeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStudentBornDateDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStudentBornDateMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStudentBornDateYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStudentBornDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStudentCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStudentCode))
                .addGap(18, 18, 18)
                .addComponent(lblSchool)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblSchoolID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSchoolName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSchoolID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSchoolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(txtEspacioVacio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDone)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtStudentBornDateDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentBornDateDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentBornDateDayActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtStudentGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentGenderActionPerformed

    private void txtStudentHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentHeightActionPerformed

    private void txtStudentWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentWeightActionPerformed

    private void txtSchoolIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolIDActionPerformed

    private void txtSchoolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSchoolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSchoolNameActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        if (txtStudentID.getText().trim().equalsIgnoreCase("") || txtStudentName.getText().trim().equalsIgnoreCase("") || txtStudentWeight.getText().trim().equalsIgnoreCase("") || txtStudentHeight.getText().trim().equalsIgnoreCase("") || txtStudentBornDateDay.getText().trim().equalsIgnoreCase("") || txtStudentGender.getText().trim().equalsIgnoreCase("") || txtStudentCode.getText().trim().equalsIgnoreCase("") || txtSchoolID.getText().trim().equalsIgnoreCase("") || txtSchoolName.getText().trim().equalsIgnoreCase(""))
        {
            txtEspacioVacio.setVisible(true);
        }
        else {
            txtEspacioVacio.setVisible(false);
            studentController.setStudentID(this.txtStudentID.getText().trim());
            studentController.setStudentName(this.txtStudentName.getText().trim());
            studentController.setlastName(this.txtStudentLastName.getText().trim());
            studentController.setWeight(this.txtStudentWeight.getText().trim());
            studentController.setHeight(this.txtStudentHeight.getText().trim());
            try {
                studentController.setBornDate(this.txtStudentBornDateDay.getText().trim()+"/"+this.txtStudentBornDateMonth.getText().trim()+"/"+this.txtStudentBornDateYear.getText().trim());
            } catch (Exception ex) {
                Logger.getLogger(mainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
            studentController.setGender(this.txtStudentGender.getText().trim());
            studentController.setCode(this.txtStudentCode.getText().trim());
            //studentController.setFacultyId(this.txtSchoolID.getText().trim());
            //studentController.setFacultyName(this.txtSchoolName.getText().trim());
            System.out.println("datos"+this.studentController.toString());
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void txtStudentCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentCodeActionPerformed

    private void txtStudentBornDateMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentBornDateMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentBornDateMonthActionPerformed

    private void txtStudentBornDate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentBornDate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentBornDate2ActionPerformed

    private void txtStudentBornDateYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentBornDateYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentBornDateYearActionPerformed

    private void txtStudentLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentLastNameActionPerformed

    private void txtStudentBornDateDayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentBornDateDayMouseClicked
        if(oned == false) {
            txtStudentBornDateDay.setText("");
            txtStudentBornDateDay.setForeground(Color.BLACK);
            oned = true;
        }
        
    }//GEN-LAST:event_txtStudentBornDateDayMouseClicked

    private void txtStudentBornDateMonthMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentBornDateMonthMouseClicked
        if(onem == false) {
            txtStudentBornDateMonth.setText("");
            txtStudentBornDateMonth.setForeground(Color.BLACK);
            onem = true;        
        }
    }//GEN-LAST:event_txtStudentBornDateMonthMouseClicked

    private void txtStudentBornDateYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStudentBornDateYearMouseClicked
        if(oney == false) {
            txtStudentBornDateYear.setText("");
            txtStudentBornDateYear.setForeground(Color.BLACK);
            oney = true;
        }
    }//GEN-LAST:event_txtStudentBornDateYearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSchool;
    private javax.swing.JLabel lblSchoolID;
    private javax.swing.JLabel lblSchoolName;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JLabel lblStudentBornDate;
    private javax.swing.JLabel lblStudentCode;
    private javax.swing.JLabel lblStudentGender;
    private javax.swing.JLabel lblStudentHeight;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblStudentLastName;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblStudentWeight;
    private javax.swing.JLabel txtEspacioVacio;
    private javax.swing.JTextField txtSchoolID;
    private javax.swing.JTextField txtSchoolName;
    private javax.swing.JTextField txtStudentBornDate2;
    private javax.swing.JTextField txtStudentBornDateDay;
    private javax.swing.JTextField txtStudentBornDateMonth;
    private javax.swing.JTextField txtStudentBornDateYear;
    private javax.swing.JTextField txtStudentCode;
    private javax.swing.JTextField txtStudentGender;
    private javax.swing.JTextField txtStudentHeight;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextField txtStudentLastName;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentWeight;
    // End of variables declaration//GEN-END:variables
}
